### ISSUE TITLE
Validation: Verify service names are never empty

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#682]
in both, Config.Name and names of outbounds.

**Comment by breerly** [comment]
Just checked, we're good:

```
--- FAIL: TestEmptyServiceNamesNotAllowed (0.00s)
panic: yarpc.NewDispatcher expects a service name [recovered]
	panic: yarpc.NewDispatcher expects a service name

goroutine 286 [running]:
panic(0x3c5e20, 0xc420266950)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4201589c0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:579 +0x25d
panic(0x3c5e20, 0xc420266950)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:458 +0x243
go.uber.org/yarpc.NewDispatcher(0x463cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/grayson/gocode/src/go.uber.org/yarpc/dispatcher.go:95 +0x485
go.uber.org/yarpc_test.TestEmptyServiceNamesNotAllowed(0xc4201589c0)
	/Users/grayson/gocode/src/go.uber.org/yarpc/dispatcher_test.go:329 +0x4d
testing.tRunner(0xc4201589c0, 0x4a1740)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:646 +0x2ec
FAIL	go.uber.org/yarpc	0.123s
go.uber.org/yarpc - [dev●] » fg
[1]  + 97076 continued  nvim

[1]  + 97076 suspended  nvim
go.uber.org/yarpc - [dev●] » go test .
--- FAIL: TestEmptyServiceNamesNotAllowed (0.00s)
panic: no outbound set for service "" in dispatcher [recovered]
	panic: no outbound set for service "" in dispatcher

goroutine 256 [running]:
panic(0x3c5f20, 0xc42000de60)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420090180)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:579 +0x25d
panic(0x3c5f20, 0xc42000de60)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:458 +0x243
go.uber.org/yarpc.convertOutbounds(0xc420017bc0, 0x0, 0x0, 0x0, 0x0, 0x5343d59117a67803)
	/Users/grayson/gocode/src/go.uber.org/yarpc/dispatcher.go:117 +0x51c
go.uber.org/yarpc.NewDispatcher(0x463f51, 0x2, 0x0, 0x0, 0x0, 0xc420017bc0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/grayson/gocode/src/go.uber.org/yarpc/dispatcher.go:105 +0x11a
go.uber.org/yarpc_test.TestEmptyServiceNamesNotAllowed(0xc420090180)
	/Users/grayson/gocode/src/go.uber.org/yarpc/dispatcher_test.go:332 +0x14d
testing.tRunner(0xc420090180, 0x4a1840)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/Cellar/go/1.7.4_1/libexec/src/testing/testing.go:646 +0x2ec
FAIL	go.uber.org/yarpc	0.112s
```
